import { DataTypes } from "sequelize";
import sequelize from "../database/db.js";


export const MemberAgent = sequelize.define('MemberAgent', {
    agentId: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    email: {
        type: DataTypes.STRING(255),
        allowNull: false,
        unique: true
    },
    firstname: {
        type: DataTypes.STRING(255),
        allowNull: false
    },
    lastname: {
        type: DataTypes.STRING(255),
        allowNull: false
    },
    phone: {
        type: DataTypes.STRING(255),
        allowNull: true
    },
    gender: {
        type: DataTypes.STRING,
        allowNull: true
    },
    photo: {
        type: DataTypes.STRING,
        allowNull: true
    },
    businessName: {
        type: DataTypes.STRING,
        allowNull: true,
        defaultValue: null
    },
    password: {
        type: DataTypes.STRING,
        allowNull: false
    },
    agentStatus: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: 'PENDING'
    },
    regDate: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW
    }
}, {
    timestamps: true,
    tableName: 'member_agents',
    indexes: [
        {
            name: 'idx_agent_name',
            fields: ['firstname', 'lastname']
        }
    ],
    hooks: {
        beforeCreate: (agent) => {
            if (!agent.businessName) {
                agent.businessName = `${agent.firstname} ${agent.lastname}'s Agency`;
            }
        },
        beforeUpdate: (agent) => {
            if (agent.changed('firstname') || agent.changed('lastname')) {
                const currentBusinessName = agent.businessName;
                const oldFirstName = agent.previous('firstname');
                const oldLastName = agent.previous('lastname');
                const oldAutoGenerated = `${oldFirstName} ${oldLastName}'s Agency`;
                
                if (currentBusinessName === oldAutoGenerated) {
                    agent.businessName = `${agent.firstname} ${agent.lastname}'s Agency`;
                }
            }
        }
    }
});

